CRR.Web/Pages/AddProperties.cshtml.cs
using CRR.Models;
using CRR.Web.Models;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System.Security.Claims;

namespace CRR.Web.Pages
{
	[Authorize(Roles = "landlord")]
	public class AddPropertiesModel : PageModel
    {
        private readonly HttpClient _client;
        public AddPropertiesModel(HttpClient client)
        {
            _client = client;
        }

        public async Task<IActionResult> OnGet()
        {
			ClaimsPrincipal currentUser = this.User;
			currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier)?.Value;

			Properties = await _client.GetFromJsonAsync<Property[]>($"Properties/{currentUserId}");
			
			PropertyModel = new();
			
			return Page();
        }

		[BindProperty]
		public PropertyModel PropertyModel { get; set; }
		[BindProperty]
		public Property[] Properties { get; set; }

		private string? currentUserId { get; set; }


		public async Task<IActionResult> OnPostAsync()
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}

			ClaimsPrincipal currentUser = this.User;
			var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier)?.Value;

			var prop = new Property()
			{
				ApplicationUserId = currentUserID,
				Address = PropertyModel.Address,
				City = PropertyModel.City,
				State = PropertyModel.State,
				Country = PropertyModel.Country,
				Type = PropertyModel.Type
			};

			var response = await _client.PostAsJsonAsync("Properties/upsert", prop);
			if (response.IsSuccessStatusCode)
				return RedirectToPage("./AddProperties");

			else throw new Exception();
		}
	}
}

CRR.Web/Pages/AddReview.cshtml.cs
using CRR.Models;
using CRR.Web.Models;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

using System.IO.Compression;
using System.Security.Claims;

namespace CRR.Web.Pages
{
	[Authorize(Roles = "landlord")]
    public class AddReviewModel : PageModel
    {
        private readonly HttpClient _client;
        public AddReviewModel(HttpClient agent)
        {
            _client = agent;
        }
		
        public async Task OnGet()
        {
            Properties = await GetPropertiesAsync();
            ReviewModel = new();
        }

		[BindProperty]
        public Property[] Properties { get; set; }

		[BindProperty]
		public TenantReviewModel ReviewModel { get; set; }

		private async Task<Property[]> GetPropertiesAsync()
		{
            ClaimsPrincipal currentUser = this.User;
            string? currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            return await _client.GetFromJsonAsync<Property[]>($"Properties/{currentUserId}");
        }

        public async Task<IActionResult> OnPostUploadAsync()
        {
			Properties = await GetPropertiesAsync();
			
			if (!ModelState.IsValid)
			{
                return Page();
			}

            ClaimsPrincipal currentUser = this.User;
            string? currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var review = new TenantReview
            {
                ApplicationUserId = currentUserId,
				TenantCNIC = ReviewModel.TenantCNIC,
				TenantName = ReviewModel.TenantName,
				Date = DateTime.Now,
				StayDuration = ReviewModel.StayDuration,
				Details = ReviewModel.Details,
				PropertyId = ReviewModel.PropertyId,
                RatingOverview = ReviewModel.Ratings.Count() > 0 ? Math.Round(ReviewModel.Ratings.Average(r => r.Value), 0, MidpointRounding.ToPositiveInfinity) : 1
            };
			
			foreach (var item in ReviewModel.Attachments)
			{
				using (var memoryStream = new MemoryStream())
				{
					// Upload the file if less than 5 MB
					if (memoryStream.Length < 5242880)
					{
                        await item.CopyToAsync(memoryStream);
						var file = new Attachment()
						{
                            Name = item.FileName,
							Content = memoryStream.ToArray()
						};

                        review.Attachments.Add(file);
					}
				}
			}

            review.Ratings.AddRange(ReviewModel.Ratings);

            var res = await _client.PostAsJsonAsync("reviews/add", review);
			if (res.IsSuccessStatusCode)
			{
                TempData["Notification"] = "Review was successfully published";
                //review = await res.Content.ReadFromJsonAsync<TenantReview>();
			}
			else
			{
                ModelState.AddModelError("File", await res.Content.ReadAsStringAsync());
			}


			return Page();
        }
    }
}

CRR.Web/Pages/BecomeContributor.cshtml.cs
using CRR.Models;
using CRR.Web.Data;
using CRR.Web.Models;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace CRR.Web.Pages
{
    public class BecomeContributorModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
		
        private readonly HttpClient _client;
		public BecomeContributorModel(HttpClient http, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, RoleManager<IdentityRole> roleManager)
		{
			_client = http;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
		}

		[BindProperty]
		public LandlordModel Landlord { get; set; }

		public IActionResult OnGet()
        {
            Landlord = new LandlordModel();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.GetUserAsync(User);

            user.About = Landlord.About;
            user.PermanentAddress = Landlord.PermanentAdress;

            var result = await _userManager.UpdateAsync(user);

            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return Page();
            }

            if (!await _roleManager.RoleExistsAsync("landlord"))
                await _roleManager.CreateAsync(new IdentityRole("landlord"));

            if(!await _userManager.IsInRoleAsync(user, "landlord"))
                await _userManager.AddToRoleAsync(user, "landlord");
			
            await _signInManager.RefreshSignInAsync(user);
            return RedirectToPage("./AddProperties");
        }
    }
}

CRR.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System.Diagnostics;

namespace CRR.Web.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

CRR.Web/Pages/Home.cshtml.cs
using CRR.Models;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.JSInterop;

namespace CRR.Web.Pages
{
	[Authorize]
    public class HomeModel : PageModel
    {
        private HttpClient _client;

        public HomeModel(HttpClient agent)
		{
            _client = agent;
        }

        public async Task OnGetAsync()
        {
			if (!string.IsNullOrEmpty(Keyword))
			{
                Reviews = await _client.GetFromJsonAsync<List<TenantReview>>($"reviews/search/{Keyword}");
            }
			else
			{
                Reviews = new List<TenantReview>();
			}
			
			Insight = await _client.GetFromJsonAsync<Insight>("insights");
        }

        public IList<TenantReview>? Reviews { get; set; } = default!;
        [BindProperty(SupportsGet = true)]
        public string Keyword { get; set; }
		public Insight Insight { get; set; }

		public async Task<IActionResult> OnPostDownloadAsync(int id)
		{
            var res = await _client.GetAsync($"attachments/{id}");
			if (res.IsSuccessStatusCode)
			{
				Attachment? attachment = await res.Content.ReadFromJsonAsync<Attachment>();
				
                return File(attachment.Content, "application/force-download", attachment?.Name);
            }
			else
			{
                TempData["Notification"] = "Failed to download attachment";
			}
			
            return Page();
        }

    }
	
       public class Insight
	{
		public int Properties { get; set; }
		public int Reviews { get; set; }
		public int Users { get; set; }
	}

}

CRR.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CRR.Web.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;

		public IndexModel(ILogger<IndexModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{

		}
	}
}

CRR.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CRR.Web.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

CRR.Web/Pages/AddReview.cshtml
@page
@using CRR.Models
@model CRR.Web.Pages.AddReviewModel
@{
	ViewData["Title"] = "Review Tenant";
}



<div class="container my-3">
	
	@if(TempData["Notification"] != null)
	{
		<div class="alert alert-info alert-dismissible fade show" role="alert">
	    @TempData["Notification"]
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
	}

	<div class="shadow p-3">
		<h4>Review Tenant</h4>
		<div class="row">
			<div class="col-lg-10">
				<p class="text-muted"><small>Please provide the following information and necessary details related to your tenants to proceed.</small></p>
			</div>
			<div class="col-lg-2">
				@*<a class="btn btn-outline-primary btn-sm" href="#"><small>My Contributions</small></a>*@
			</div>
		</div>
		<hr/>
	</div>

	<div class="card mt-3 p-3">
		<div class="card-body">
			<form method="post" enctype="multipart/form-data">
				<h5>Details</h5>
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="row">
					<div class="col-md-6">
						<div class="my-1">
							<input type="hidden" asp-for="Properties" />
							<label asp-for="ReviewModel.PropertyId" class="form-label">Property</label>
							<select asp-for="ReviewModel.PropertyId" class="form-select">
								@foreach (var prop in Model.Properties)
								{
									<option value="@prop.Id">
										<p class="text-primary"><strong>@prop.Address,</strong></p>
										<div class="row">
											<div class="col-sm-4">
												<p class="text-secondary"><small>@prop.City,</small></p>
											</div>
											<div class="col-sm-4">
												<p class="text-secondary"><small>@prop.State,</small></p>
											</div>
											<div class="col-sm-4">
												<p class="text-secondary"><small>@prop.Country</small></p>
											</div>
											<div class="col-4">
												<p class="text-info"><small>(@prop.Type)</small></p>
											</div>
										</div>
									</option>
								}
							</select>
							<span asp-validation-for="ReviewModel.PropertyId" class="text-danger">
							</span>
						</div>
					</div>
					<div class="col-md-6">
						<div class="my-1">
							<label asp-for="ReviewModel.StayDuration" class="form-label">Stay Duration</label>
							<input asp-for="ReviewModel.StayDuration" class="form-control" type="text" />
							<span asp-validation-for="ReviewModel.StayDuration" class="text-danger">
							</span>
						</div>
					</div>
					<div class="col-md-6">
						<div class="my-1">
							<label asp-for="ReviewModel.TenantName" class="form-label">Tenant Name</label>
							<input asp-for="ReviewModel.TenantName" class="form-control" type="text" />
							<span asp-validation-for="ReviewModel.TenantName" class="text-danger">
							</span>
						</div>
					</div>
					<div class="col-md-6">
						<div class="my-1">
							<label asp-for="ReviewModel.TenantCNIC" class="form-label">Tenant CNIC</label>
							<input asp-for="ReviewModel.TenantCNIC" class="form-control" type="text" />
							<span asp-validation-for="ReviewModel.TenantCNIC" class="text-danger">
							</span>
						</div>
					</div>
					<div class="my-1">
						<label asp-for="ReviewModel.Details" for="aboutInput" class="form-label">Details</label>
						<textarea asp-for="ReviewModel.Details" class="form-control"  id="aboutInput" aria-describedby="aboutHelp"></textarea>
						<div id="aboutHelp" class="form-text">Tell us additional details about the tenant. For example: What went right or what challenges you faced</div>
						<span asp-validation-for="ReviewModel.Details" class="text-danger"></span>
					</div>
					<hr class="mt-1"/>
					<h5>Ratings</h5>
					<div class="card border-1 p-3">
						@for(int i = 0; i < Model.ReviewModel.Ratings.Count(); i++)
						{
							<div class="mt-1 d-flex justify-content-between align-items-center">
								<h5 class="review-stat">@Model.ReviewModel.Ratings[i].Description</h5>
								<input type="hidden" asp-for="ReviewModel.Ratings[i].Description" value="@Model.ReviewModel.Ratings[i].Description"/>
								<div class="ratings">
									<select asp-for="ReviewModel.Ratings[i].Value" class="border-0 form-select-sm shadow-sm" style="font-family: 'FontAwesome'; color: #fbc634;">
										<option value="0">
											Select Rating
										</option>
										<option value="1">
											&#xf005;
										</option>
										<option value="2">
											&#xf005; &#xf005;
										</option>
										<option value="3">
											&#xf005; &#xf005; &#xf005;
										</option>
										<option value="4">
											&#xf005; &#xf005; &#xf005; &#xf005;
										</option>
										<option value="5">
											&#xf005; &#xf005; &#xf005; &#xf005; &#xf005;
										</option>
									</select>
									@*<a id="r1" name="r1" role="button" onclick="console.log('@item.Description star-1')"><i class="fa fa-star"></i></a>
									<a role="button" onclick="console.log('@item.Description star-2')"><i class="fa fa-star"></i></a>
									<a role="button" onclick="console.log('@item.Description star-3')"><i class="fa fa-star"></i></a>
									<a role="button" onclick="console.log('@item.Description star-4')"><i class="fa fa-star"></i></a>
									<a role="button" onclick="console.log('@item.Description star-5')"><i class="fa fa-star"></i></a>*@
								</div>
							</div>
						}
						@*@foreach (var item in Model.ReviewModel.Ratings)
						{
							<div class="mt-1 d-flex justify-content-between align-items-center">
								<h5 class="review-stat">@item.Description</h5>
								<div class="ratings">
									<select asp-for="ReviewModel.Ratings[0].Value" class="border-0 form-select-sm shadow-sm" style="font-family: 'FontAwesome'; color: #fbc634;">
										<option value="0">
											Select Rating
										</option>
										<option value="1">
											&#xf005;
										</option>
										<option value="2">
											&#xf005; &#xf005;
										</option>
										<option value="3">
											&#xf005; &#xf005; &#xf005;
										</option>
										<option value="4">
											&#xf005; &#xf005; &#xf005; &#xf005;
										</option>
										<option value="5">
											&#xf005; &#xf005; &#xf005; &#xf005; &#xf005;
										</option>
									</select>
								</div>
							</div>
						}*@
					</div>

					<hr />
					<h5>Attachments</h5>
					<div class="form-control mt-1 mb-2">
						<input type="file" asp-for="ReviewModel.Attachments" multiple/>
						<div class="form-text">Please choose files having size smaller than 5mb.</div>
					</div>

					<input asp-page-handler="Upload" type="submit" class="btn btn-primary btn-sm" value="Submit"/>
				</div>
			</form>
		</div>
	</div>
		

	<hr/>
	<a class="page-link" asp-page="./home">&larr; Back to homepage</a>
</div>

CRR.Web/Pages/Home.cshtml
@page
@using CRR.Models
@using System.IO
@using Microsoft.JSInterop
@inject IJSRuntime JS
@model CRR.Web.Pages.HomeModel
@{
    ViewData["Title"] = "Home";
}

<div class="container mt-2">
        
    @if (!User.IsInRole("landlord"))
    {
        <div class="h-100 p-5 bg-light border rounded-3 mb-2">
        <h4 class="h-5">Become a contributor!</h4>
        <p>If you ever happened to interact with tenents that damaged your appartments or houses after taking them on rent, please
            upload their details here so that other people can get benefit from it and keep such tenents away from their
            properties. Upload your tenent details <a class="btn btn-sm btn-outline-secondary" asp-page="/becomeContributor">here.</a>
        </p>
        </div>
    }
    else
    {
        <div class="card my-2 p-2 shadow border-0">
            <div class="card-body">
                <div class="row">
                        <h5>Welcome to Central Rent Register!</h5>
                    <div class="col-md-10">
                        <small class="text-muted">Add your tenant reviews or search for tenants reviewed by other landlords or house owners.</small>
                    </div>
                    <div class="col-md-2 d-flex justify-content-end">
                        <a class="btn btn-sm btn-secondary" asp-page="./AddReview">Review your Tenants</a>
                    </div>
                </div>
            </div>
        </div>
    }

    <div class="card my-2 shadow-sm">
        <div class="card-body">
            <h5>Search Tenents</h5>
            <small class="text-muted">Search by tenent CNIC, first names, last names or phone numbers to get property owner's reviews...</small>
            <form>
                <div class="row">
                    <div class="col-md-11">
                        <input class="form-control form-control-dark w-100 rounded-top mt-2 border-1" asp-for="Keyword" type="text" placeholder="Search.." aria-label="Search">
                    </div>
                    <div class="col-md-1">
                        <button type="submit" class="btn btn-outline-primary mt-2">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <h5>Search Results</h5>

    @*First row of results*@
    @if(Model.Reviews.Count() == 0)
    {
        <div class="alert alert-info" role="alert">
		    No matching tenants.
		</div>
    }
    else
    {
        <div class="row">
        @foreach (var review in Model.Reviews)
        {
            <div class="col-md-6">
                <div class="card p-3 my-1 shadow-sm">
                    <div class="card-title">
                        <strong>@review?.TenantName</strong>
                    </div>
                    <div class="card-subtitle">
                        <div class="row">
                            <div class="col-md-9">
                                <small class="text-muted"><i class="fa fa-building"></i> @review?.Property?.Address, @review?.Property?.City, @review?.Property?.State, @review?.Property?.Country</small>
                            </div>
                            <div class="d-flex justify-content-end col-md-3">
                                <button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#r_@review?.Id"><small><i class="fa fa-eye"></i> <i> View Details</i></small></button>
                            </div>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <div class="container d-flex justify-content-center align-items-center">
                            <div class="card border-0 p-3">
                                <div class="d-flex mb-4 justify-content-between align-items-center">
                                        <div class="ratings">
                                        @for (int i = 1; i < 6; i++)
                                        {
                                            if(i <= review?.RatingOverview)
                                            {
                                                <i class="fa fa-star rating-color"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-star"></i>
                                            }
                                        }
                                    </div>
                                        <h5 class="review-count">@review?.RatingOverview stars</h5>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            @*Modal*@
            <div class="modal fade py-3" role="dialog" tabindex="-1" id="r_@review?.Id" aria-hidden="true" aria-labelledby="@review?.TenantName">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                    <div class="modal-content rounded-3 shadow">
                        <div class="modal-header border-bottom-0">
                            <h5 class="modal-title" id="@review?.TenantName">@review?.TenantName</h5>
        					<button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
        
                        <div class="modal-body p-5 pt-1">
                            <hr/>
                            <h6><i class="fa fa-star"></i> Overview</h6>
                            <div class="height-100 container d-flex justify-content-center align-items-center">
                                <div class="card border-0 p-3">
                                    <div class="d-flex mb-4 justify-content-between align-items-center">
                                        <div class="ratings">
                                        @for (int i = 1; i < 6; i++)
                                        {
                                            if(i <= review?.RatingOverview)
                                            {
                                                <i class="fa fa-star rating-color"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-star"></i>
                                            }
                                        }
                                    </div>
                                        <h5 class="review-count">@review?.RatingOverview stars</h5>
                                    </div>
                                    
                                @foreach (var rating in review.Ratings)
                                {
                                    <div class="mt-1 d-flex justify-content-between align-items-center">
                                        <h5 class="review-stat">@rating.Description</h5>
                                        <div class="small-ratings">
                                            @for (int i = 1; i < 6; i++)
                                            {
                                                if(i <= rating.Value)
                                                {
                                                    <i class="fa fa-star rating-color"></i>
                                                }
                                                else
                                                {
                                                    <i class="fa fa-star"></i>
                                                }
                                            }
                                        </div>
                                    </div>
                                }
                                </div>
                            </div>
                            <hr/>
                            <h6><i class="fa fa-file-text"></i> Details</h6>
                            <p>
                                @review.Details
                            </p>
        
                            <hr/>
                            <h6><i class="fa fa-calendar-o"></i> Stay Duration</h6>
                            <p>
                                @review.StayDuration
                            </p>
        
                            <hr/>
                            <h6><i class="fa fa-building"></i> Location</h6>
                            <p>
                                @review?.Property?.Address, @review?.Property?.City, @review?.Property?.State, @review?.Property?.Country
                            </p>
        
                            <hr/>
                            <h6><i class="fa fa-address-book"></i> CNIC</h6>
                            <p>
                                @review?.TenantCNIC
                            </p>
        
                            
                            <hr/>
                            <h6><i class="fa fa-link"></i> Attachments</h6>
        
                            @if(review?.Attachments.Count == 0)
                            {
                                <div class="alert alert-info" role="alert">
        		                    No attachments provided.
        		                </div>
                            }
                            else
                            {
                                @foreach (var item in review.Attachments)
                                {
                                    <form asp-page-handler="Download" method="post" asp-route-id="@item.Id">
                                        <button type="submit" class="btn btn-sm btn-outline-secondary my-1"><i class="fa fa-download"></i> @item.Name</button>
                                    </form>
                                }

                                @if(TempData["Notification"] != null)
                                {
                                    <div class="alert alert-info alert-dismissible fade show" role="alert">
	                                    @TempData["Notification"]
	                                	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	                                </div>
                                }
                            }
        
                            <hr/>
                            <div class="card">
                                <div class="card-header">
                                  About reviewer
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">@review?.ApplicationUser?.UserName</h5>
                                    <p class="card-text">
                                        @review?.ApplicationUser?.About
                                    </p>
                                    @*<div class="d-flex justify-content-end">
                                        <a href="#" class="btn btn-outline-primary btn-sm">View Profile</a>
                                    </div>*@
                                </div>
                                <div class="card-footer d-flex justify-content-end text-muted">
                                  <small>Posted on @review?.Date.ToShortDateString()</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        </div>
        <div class="h-100"></div>
        <div class="d-flex justify-content-center">
            <p class="text-danger"><small>***End of Results***</small></p>
        </div>
    }


    <!-- Insights -->
    <div class="card my-2">
        <div class="card-body">
            <h6 class="card-title">Platform Insights</h6>
          <div class="row my-2">
              <div class="col-4 box-shadow">
                  <div class="card">
                      <div class="card-body">
                          <h6><i class="fa fa-files-o"></i> @Model.Insight.Reviews reviews</h6>
                      </div>
                  </div>
              </div>
              <div class="col-4 shadow-sm">
                  <div class="card">
                      <div class="card-body">
                          <h6><i class="fa fa-users"></i> @Model.Insight.Users Users</h6>
                      </div>
                  </div>
              </div>
              <div class="col-4 shadow-sm">
                  <div class="card">
                      <div class="card-body">
                          <h6><i class="fa fa-building"></i> @Model.Insight.Properties Properties</h6>
                      </div>
                  </div>
              </div>
          </div>
        </div>
    </div>
</div>